apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: <Instance-Role_Arn>  // Make sure to provide instance role arn, not profile. Get it from the resource section of your cloudformation script.
      username: system:node:{{EC2PublicDNSName}} // You can also change it to >> EC2PrivateDNSName
      groups:
        - system:bootstrappers
        - system:nodes