apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-sample-linux-deployment
  namespace: eks-sample-linux-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-webapp
  template:
    metadata:
      labels:
        app: nginx-webapp
    spec:
      containers:
      - name: nginx
        image: nginx:1.23
        ports:
        - name: http
          containerPort: 80

---
apiVersion: v1
kind: Service 
metadata:
  name: eks-sample-linux-service
  namespace: eks-sample-linux-deployment
spec:
  ports:
    - port: 443
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app: nginx-webapp

