apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: default
  labels:
    app: nginx-lab
spec:
  replicas: 1 # tells deployment to run 2 pods matching the template
  selector:
    matchLabels:
      app: nginx-lab
  template:
    metadata:
      labels:
        app: nginx-lab
    spec:
      containers:
      - name: nginx
        image: nginx:1.23
        resources:
          limits:
            memory: 512Mi
            cpu: "1.5"
          requests:
            memory: 256Mi
            cpu: "0.5"
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 433
