apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: default
spec:
  selector:
    app: nginx-lab
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80 # This may change, based on the port exposed to the container. 
  type: LoadBalancer
